### ISSUE TITLE
Internal URL found in project

### ISSUE THREAD

**Issue by jonathanbaker7** [SAP/cloud-realspend-expenses-uploader#1]
The file [run.sh](https://github.com/SAP/cloud-realspend-expenses-uploader/blob/0925cece6293b2893b08c423eb3a80776d3ced79/run.sh) has a proxy server element in it that references our internal SAP proxy server.  This might be an artifact from your internal work. 

> --hcp_proxy=proxy.wdf.sap.corp:8080

The Open Source policy from SAP is to remove any internal references from work that has been contributed to the public domain.  If you would, please, remove this reference from the file, I would appreciate it.  This will prevent the project from coming up in our scans in the future.

Thank you,
Jonathan Baker

**Comment by fafl-sap** [comment]
done
