### ISSUE TITLE
SAP artifact in a Java code file

### ISSUE THREAD

**Issue by jonathanbaker7** [SAP/cloud-realspend-expenses-uploader#3]
The file [IntegrationTest.java](https://github.com/SAP/cloud-realspend-expenses-uploader/blob/e13feab0ca0296d146fc1e383d236deeb8089f5c/src/test/java/com/sap/expenseuploader/IntegrationTest.java) contains a reference to an internal SAP server:

```
 {

        String[] args = {
            "--from",               "20150301",
            "--to",                 "20150501",
            "--controlling-area",   "0001",
            "--input_erp",          "system",
            "--output_hcp",
            "--output_cli",
            "--hcp_url",            "https://bmsfin-<your account here>.hanatrial.ondemand.com/core/basic/api/v1",
            "--hcp_user",           "your username here",
            "--hcp_password",       new String(Base64.decodeBase64("your password in base64 here".getBytes())),
            "--hcp_proxy",          "proxy.wdf.sap.corp:8080",
            "--budgets",
            "--resume"
        };
```

Specifically, the server:

    proxy.wdf.sap.corp

This artifact won't work outside the SAP firewall.

SAP Open Source runs regular scans looking for artifacts in the code which might indicate our internal code has accidentally released in to the Open Source stream. This file continues to show up in our scans. Can you please fix it, or remove it, so that it no longer shows up as an error?

Thank you.

**Comment by fafl-sap** [comment]
done
